### ISSUE TITLE
Fails to load some fonts contained in PDF

### ISSUE THREAD

**Issue by vbkaisetsu** [pdf-rs/font#2]
I opened the following PDF using pdf-rs and tried to render it using pdf_render.
https://arxiv.org/pdf/1912.13318.pdf
However, I got the following error:
```
[2021-05-05T04:24:11Z DEBUG font::type1] FontDict keys: /"FontInfo", /"CharStrings", /"FontName", /"Encoding", /"FontBBox", /"FontMatrix", /"FontType", /"PaintType", /"Private"
[2021-05-05T04:24:11Z DEBUG font::type1] Private keys: /"MinFeature", /"BlueFuzz", /"Subrs", /"FamilyOtherBlues", /"lenIV", /"password", /"FamilyBlues", /"BlueScale", /"LanguageGroup", /"StemSnapV", /"ExpansionFactor", /"OtherSubrs", /"StemSnapH", /"BlueValues", /"ForceBold", /"OtherBlues", /"NP", /"RD", /"ND", /"BlueShift", /"StdHW", /"StdVW"
[2021-05-05T04:24:11Z DEBUG font::type1] FontName: Some(/"GLEUEB+LinLibertineT")
[2021-05-05T04:24:11Z DEBUG font::type1] FontInfo: Some()
thread 'main' panicked at 'tried to cast a float to int', /Users/k-akabe/.cargo/git/checkouts/font-06ada714b08e6cdd/a2ff1d2/src/lib.rs:208:32
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/k-akabe/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: font::Value::to_int
             at /Users/k-akabe/.cargo/git/checkouts/font-06ada714b08e6cdd/a2ff1d2/src/lib.rs:208:32
   2: font::type1::charstring
             at /Users/k-akabe/.cargo/git/checkouts/font-06ada714b08e6cdd/a2ff1d2/src/type1.rs:287:31
   3: font::type1::Type1Font::from_vm
             at /Users/k-akabe/.cargo/git/checkouts/font-06ada714b08e6cdd/a2ff1d2/src/type1.rs:125:13
   4: font::type1::Type1Font::parse_postscript
             at /Users/k-akabe/.cargo/git/checkouts/font-06ada714b08e6cdd/a2ff1d2/src/type1.rs:73:9
   5: font::parse
             at /Users/k-akabe/.cargo/git/checkouts/font-06ada714b08e6cdd/a2ff1d2/src/lib.rs:419:29
   6: pdf_render::cache::Cache::load_font
             at /Users/k-akabe/.cargo/git/checkouts/pdf_render-56211f49c16f7190/4b123c5/render/src/cache.rs:104:38
   7: pdf_render::cache::Cache::render_page
             at /Users/k-akabe/.cargo/git/checkouts/pdf_render-56211f49c16f7190/4b123c5/render/src/cache.rs:166:13
   8: pftest::main
             at ./src/main.rs:112:26
   9: core::ops::function::FnOnce::call_once
             at /Users/k-akabe/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

**Comment by vbkaisetsu** [comment]
According to the Charstring Number Encoding section in the Type 1 and Type 2 specifications [1, 2], the next 4 bytes after 255 is a signed integer.

> if the charstring byte contains the value 255, the next four bytes  indicate  a  two’s  complement  signed  integer.  The first  of  these  four  bytes  contains  the  highest  order  bits,  the second byte contains the next higher order bits and the fourth byte  contains  the  lowest  order  bits.  Thus,  any  32-bit  signed integer may be encoded in 5 bytes in this manner (the 255 byte plus 4 more bytes).

However, `charstring` function divides a retrieved integer by 65536.

https://github.com/pdf-rs/font/blob/a2ff1d24376f3e1a61920d0384cf2e413654d932/src/type1.rs#L456-L459
https://github.com/pdf-rs/font/blob/a2ff1d24376f3e1a61920d0384cf2e413654d932/src/type2.rs#L494-L498

[1] https://adobe-type-tools.github.io/font-tech-notes/pdfs/T1_SPEC.pdf
[2] https://adobe-type-tools.github.io/font-tech-notes/pdfs/5177.Type2.pdf

**Comment by s3bk** [comment]
good catch.
